// lib/collage-templates.ts
import { CollageTemplate } from "@/types/collage-template";

export const COLLAGE_TEMPLATES: CollageTemplate[] = [
  // 1. Scrapbook: 旅の思い出をマスキングテープや手書き風ノートでコラージュ (3-5枚)
  {
    id: "scrapbook_001",
    name: "トラベル・スクラップブック (3-5枚)",
    style: "scrapbook",
    supportedPhotoCount: { min: 3, max: 5 },
    aspect: "4:5",
    background: "craft",
    description: "クラフト紙にテープ留めと手書き風スタンプで彩る温かみのあるレイアウト",
    slots: [
      {
        role: "mainPhoto",
        x: 0.08,
        y: 0.10,
        width: 0.54,
        height: 0.52,
        rotationRange: [-3, 3],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "tape",
      },
      {
        role: "secondaryPhoto",
        x: 0.50,
        y: 0.16,
        width: 0.42,
        height: 0.38,
        rotationRange: [3, 8],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "subPhoto",
        x: 0.16,
        y: 0.58,
        width: 0.40,
        height: 0.35,
        rotationRange: [-5, -1],
        zIndex: 4,
        preferredOrientation: "square",
        frameStyle: "tape",
      },
      {
        role: "cutout",
        x: 0.54,
        y: 0.52,
        width: 0.38,
        height: 0.38,
        rotationRange: [2, 6],
        zIndex: 5,
        preferredOrientation: "any",
        frameStyle: "polaroid",
        optional: true,
      },
      {
        role: "subPhoto",
        x: 0.32,
        y: 0.45,
        width: 0.36,
        height: 0.32,
        rotationRange: [-4, 4],
        zIndex: 6,
        preferredOrientation: "any",
        frameStyle: "tape",
        optional: true,
      },
    ],
  },

  // 2. Scrapbook Deluxe: たくさんの写真(5-8枚)をしっかり収めるデラックス版 (重なりを抑えた見やすい整列スクラップ)
  {
    id: "scrapbook_deluxe_001",
    name: "スクラップブック・デラックス (5-8枚)",
    style: "scrapbook",
    supportedPhotoCount: { min: 5, max: 8 },
    aspect: "4:5",
    background: "craft",
    description: "5枚以上の写真が隠れず綺麗に見える、すっきりした整列スクラップ",
    slots: [
      {
        role: "mainPhoto",
        x: 0.05,
        y: 0.08,
        width: 0.43,
        height: 0.28,
        rotationRange: [-2, 1],
        zIndex: 2,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "secondaryPhoto",
        x: 0.52,
        y: 0.08,
        width: 0.43,
        height: 0.28,
        rotationRange: [1, 3],
        zIndex: 2,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.05,
        y: 0.38,
        width: 0.43,
        height: 0.28,
        rotationRange: [1, 3],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.52,
        y: 0.38,
        width: 0.43,
        height: 0.28,
        rotationRange: [-2, 1],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "subPhoto",
        x: 0.05,
        y: 0.68,
        width: 0.43,
        height: 0.26,
        rotationRange: [-1, 2],
        zIndex: 4,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "subPhoto",
        x: 0.52,
        y: 0.68,
        width: 0.43,
        height: 0.26,
        rotationRange: [1, 3],
        zIndex: 4,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
      },
      {
        role: "cutout",
        x: 0.35,
        y: 0.52,
        width: 0.30,
        height: 0.24,
        rotationRange: [-3, 3],
        zIndex: 6,
        preferredOrientation: "any",
        frameStyle: "tape",
        optional: true,
      },
    ],
  },

  // 3. Polaroid Gallery: ポラロイド写真を5〜8枚並べるギャラリー (重ならない2列×3段)
  {
    id: "polaroid_gallery_001",
    name: "ポラロイド・ギャラリー (5-8枚)",
    style: "polaroid",
    supportedPhotoCount: { min: 5, max: 8 },
    aspect: "4:5",
    background: "clean",
    description: "写真を隠さず綺麗に敷き詰める、2列×3段の美しいポラロイドレイアウト",
    slots: [
      {
        role: "mainPhoto",
        x: 0.05,
        y: 0.08,
        width: 0.43,
        height: 0.28,
        rotationRange: [-1.5, 1],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "polaroid",
      },
      {
        role: "secondaryPhoto",
        x: 0.52,
        y: 0.08,
        width: 0.43,
        height: 0.28,
        rotationRange: [0, 2],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.05,
        y: 0.38,
        width: 0.43,
        height: 0.28,
        rotationRange: [1, 2.5],
        zIndex: 3,
        preferredOrientation: "square",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.52,
        y: 0.38,
        width: 0.43,
        height: 0.28,
        rotationRange: [-2, 0],
        zIndex: 3,
        preferredOrientation: "square",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.05,
        y: 0.68,
        width: 0.43,
        height: 0.26,
        rotationRange: [-1.5, 1],
        zIndex: 4,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.52,
        y: 0.68,
        width: 0.43,
        height: 0.26,
        rotationRange: [0.5, 2],
        zIndex: 4,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.32,
        y: 0.52,
        width: 0.36,
        height: 0.26,
        rotationRange: [-2, 2],
        zIndex: 5,
        preferredOrientation: "any",
        frameStyle: "polaroid",
        optional: true,
      },
    ],
  },

  // 4. Polaroid Trip: ポラロイド写真 (3-4枚)
  {
    id: "polaroid_001",
    name: "ポラロイド・トリップ (3-4枚)",
    style: "polaroid",
    supportedPhotoCount: { min: 3, max: 4 },
    aspect: "4:5",
    background: "clean",
    description: "白い余白フレームと少し傾いた手作り感が可愛いポラロイド配置",
    slots: [
      {
        role: "mainPhoto",
        x: 0.25,
        y: 0.08,
        width: 0.50,
        height: 0.48,
        rotationRange: [-4, 4],
        zIndex: 4,
        preferredOrientation: "portrait",
        frameStyle: "polaroid",
      },
      {
        role: "secondaryPhoto",
        x: 0.06,
        y: 0.36,
        width: 0.40,
        height: 0.38,
        rotationRange: [-9, -4],
        zIndex: 2,
        preferredOrientation: "square",
        frameStyle: "polaroid",
      },
      {
        role: "secondaryPhoto",
        x: 0.54,
        y: 0.36,
        width: 0.40,
        height: 0.38,
        rotationRange: [4, 9],
        zIndex: 3,
        preferredOrientation: "square",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.30,
        y: 0.62,
        width: 0.38,
        height: 0.34,
        rotationRange: [-3, 3],
        zIndex: 5,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
        optional: true,
      },
    ],
  },

  // 5. Messy Memory: 写真を大胆に重ねて旅のライブ感を演出 (5-8枚)
  {
    id: "messy_many_001",
    name: "メッシー・メモリー (5-8枚)",
    style: "messy",
    supportedPhotoCount: { min: 5, max: 8 },
    aspect: "4:5",
    background: "craft",
    description: "旅の写真がたくさんある時に最適！机の上に散らばったような臨場感",
    slots: [
      {
        role: "mainPhoto",
        x: 0.05,
        y: 0.08,
        width: 0.44,
        height: 0.30,
        rotationRange: [-3, -1],
        zIndex: 2,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "secondaryPhoto",
        x: 0.51,
        y: 0.07,
        width: 0.44,
        height: 0.30,
        rotationRange: [2, 4],
        zIndex: 3,
        preferredOrientation: "portrait",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.06,
        y: 0.37,
        width: 0.44,
        height: 0.30,
        rotationRange: [1, 3],
        zIndex: 3,
        preferredOrientation: "portrait",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.50,
        y: 0.36,
        width: 0.45,
        height: 0.30,
        rotationRange: [-3, -1],
        zIndex: 4,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "subPhoto",
        x: 0.05,
        y: 0.67,
        width: 0.44,
        height: 0.27,
        rotationRange: [-2, 1],
        zIndex: 4,
        preferredOrientation: "landscape",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.51,
        y: 0.66,
        width: 0.44,
        height: 0.27,
        rotationRange: [1, 3],
        zIndex: 5,
        preferredOrientation: "portrait",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.30,
        y: 0.50,
        width: 0.38,
        height: 0.26,
        rotationRange: [-2, 2],
        zIndex: 6,
        preferredOrientation: "square",
        frameStyle: "tape",
        optional: true,
      },
    ],
  },

  // 6. Magazine Grid: 雑誌の特集ページ (4-6枚)
  {
    id: "magazine_grid_001",
    name: "マガジン・フォト特集 (4-6枚)",
    style: "magazine",
    supportedPhotoCount: { min: 4, max: 6 },
    aspect: "4:5",
    background: "magazine_white",
    description: "上部に大胆なメイン写真、下部に規則正しいグリッドを組んだ雑誌風",
    slots: [
      {
        role: "mainPhoto",
        x: 0.06,
        y: 0.08,
        width: 0.88,
        height: 0.44,
        rotationRange: [0, 0],
        zIndex: 1,
        preferredOrientation: "landscape",
        frameStyle: "clean",
      },
      {
        role: "secondaryPhoto",
        x: 0.06,
        y: 0.54,
        width: 0.28,
        height: 0.36,
        rotationRange: [0, 0],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.36,
        y: 0.54,
        width: 0.28,
        height: 0.36,
        rotationRange: [0, 0],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.66,
        y: 0.54,
        width: 0.28,
        height: 0.36,
        rotationRange: [0, 0],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.36,
        y: 0.36,
        width: 0.28,
        height: 0.24,
        rotationRange: [0, 0],
        zIndex: 3,
        preferredOrientation: "any",
        frameStyle: "polaroid",
        optional: true,
      },
    ],
  },

  // 7. Minimal Multi-Grid: 洗練された整列グリッド (4-8枚)
  {
    id: "minimal_multi_001",
    name: "ミニマル・マルチグリッド (4-8枚)",
    style: "minimal",
    supportedPhotoCount: { min: 4, max: 8 },
    aspect: "1:1",
    background: "clean",
    description: "4枚〜8枚の写真をすっきり均等に並べるモダンな正方形レイアウト",
    slots: [
      { role: "mainPhoto", x: 0.05, y: 0.05, width: 0.42, height: 0.42, rotationRange: [0, 0], zIndex: 1, preferredOrientation: "square", frameStyle: "clean" },
      { role: "secondaryPhoto", x: 0.53, y: 0.05, width: 0.42, height: 0.42, rotationRange: [0, 0], zIndex: 1, preferredOrientation: "square", frameStyle: "clean" },
      { role: "subPhoto", x: 0.05, y: 0.53, width: 0.42, height: 0.42, rotationRange: [0, 0], zIndex: 1, preferredOrientation: "square", frameStyle: "clean" },
      { role: "subPhoto", x: 0.53, y: 0.53, width: 0.42, height: 0.42, rotationRange: [0, 0], zIndex: 1, preferredOrientation: "square", frameStyle: "clean" },
      { role: "subPhoto", x: 0.28, y: 0.28, width: 0.44, height: 0.44, rotationRange: [-2, 2], zIndex: 3, preferredOrientation: "square", frameStyle: "polaroid", optional: true },
      { role: "subPhoto", x: 0.12, y: 0.70, width: 0.34, height: 0.24, rotationRange: [1, 3], zIndex: 4, preferredOrientation: "landscape", frameStyle: "tape", optional: true },
    ],
  },

  // 8. Photo Diary Full: 旅日記フルページ (4-6枚)
  {
    id: "photo_diary_full_001",
    name: "フォト・ダイアリー (4-6枚)",
    style: "photo_diary",
    supportedPhotoCount: { min: 4, max: 6 },
    aspect: "4:5",
    background: "notebook",
    description: "方眼ノートの背景に、日付や都市名スタンプと共に思い出を記録する旅日記",
    slots: [
      {
        role: "mainPhoto",
        x: 0.06,
        y: 0.12,
        width: 0.46,
        height: 0.60,
        rotationRange: [-2, 2],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "polaroid",
      },
      {
        role: "secondaryPhoto",
        x: 0.55,
        y: 0.12,
        width: 0.38,
        height: 0.32,
        rotationRange: [2, 5],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "subPhoto",
        x: 0.55,
        y: 0.46,
        width: 0.38,
        height: 0.32,
        rotationRange: [-4, -1],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "subPhoto",
        x: 0.25,
        y: 0.68,
        width: 0.50,
        height: 0.28,
        rotationRange: [1, 4],
        zIndex: 4,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
        optional: true,
      },
      {
        role: "subPhoto",
        x: 0.08,
        y: 0.45,
        width: 0.36,
        height: 0.30,
        rotationRange: [-4, 2],
        zIndex: 5,
        preferredOrientation: "square",
        frameStyle: "tape",
        optional: true,
      },
    ],
  },

  // 9. Cinema Story: スマホ全画面 (9:16) (4-7枚)
  {
    id: "cinema_story_001",
    name: "シネマ・ストーリー (4-7枚)",
    style: "magazine",
    supportedPhotoCount: { min: 4, max: 7 },
    aspect: "9:16",
    background: "dark",
    description: "スマホ全画面(9:16)で映える、シネマティックな縦長ストーリー",
    slots: [
      {
        role: "mainPhoto",
        x: 0.06,
        y: 0.06,
        width: 0.88,
        height: 0.42,
        rotationRange: [0, 0],
        zIndex: 1,
        preferredOrientation: "landscape",
        frameStyle: "film",
      },
      {
        role: "secondaryPhoto",
        x: 0.06,
        y: 0.50,
        width: 0.42,
        height: 0.28,
        rotationRange: [-2, 2],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.52,
        y: 0.50,
        width: 0.42,
        height: 0.28,
        rotationRange: [-2, 2],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.06,
        y: 0.79,
        width: 0.42,
        height: 0.18,
        rotationRange: [0, 0],
        zIndex: 2,
        preferredOrientation: "landscape",
        frameStyle: "film",
        optional: true,
      },
      {
        role: "subPhoto",
        x: 0.52,
        y: 0.79,
        width: 0.42,
        height: 0.18,
        rotationRange: [0, 0],
        zIndex: 2,
        preferredOrientation: "landscape",
        frameStyle: "film",
        optional: true,
      },
    ],
  },

  // 10. Panorama Landscape: 横写真・風景写真が主役のワイド構成 (3-5枚)
  {
    id: "landscape_panorama_001",
    name: "パノラマ・ランドスケープ (3-5枚)",
    style: "scrapbook",
    supportedPhotoCount: { min: 3, max: 5 },
    aspect: "4:5",
    background: "craft",
    description: "横向き写真やワイドな風景写真が切られずに大きく映えるワイド構成",
    slots: [
      {
        role: "mainPhoto",
        x: 0.06,
        y: 0.08,
        width: 0.88,
        height: 0.44,
        rotationRange: [-2, 2],
        zIndex: 2,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "secondaryPhoto",
        x: 0.06,
        y: 0.54,
        width: 0.42,
        height: 0.32,
        rotationRange: [2, 5],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.52,
        y: 0.54,
        width: 0.42,
        height: 0.32,
        rotationRange: [-4, -1],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "subPhoto",
        x: 0.28,
        y: 0.42,
        width: 0.44,
        height: 0.28,
        rotationRange: [-3, 3],
        zIndex: 5,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
        optional: true,
      },
    ],
  },

  // 11. Landscape Scrapbook: 横写真専用スクラップブック (4-7枚)
  {
    id: "landscape_scrapbook_001",
    name: "横写真スクラップ (4-7枚)",
    style: "scrapbook",
    supportedPhotoCount: { min: 4, max: 7 },
    aspect: "4:5",
    background: "craft",
    description: "横向き写真にぴったり合わせた横長フレームとマスキングテープの重なり",
    slots: [
      {
        role: "mainPhoto",
        x: 0.06,
        y: 0.08,
        width: 0.56,
        height: 0.38,
        rotationRange: [-3, 1],
        zIndex: 2,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "secondaryPhoto",
        x: 0.46,
        y: 0.16,
        width: 0.48,
        height: 0.34,
        rotationRange: [3, 6],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.06,
        y: 0.48,
        width: 0.50,
        height: 0.34,
        rotationRange: [1, 4],
        zIndex: 4,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.48,
        y: 0.52,
        width: 0.46,
        height: 0.32,
        rotationRange: [-4, -1],
        zIndex: 5,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "subPhoto",
        x: 0.25,
        y: 0.72,
        width: 0.50,
        height: 0.25,
        rotationRange: [-2, 2],
        zIndex: 6,
        preferredOrientation: "landscape",
        frameStyle: "tape",
        optional: true,
      },
    ],
  },

  // 12. Landscape Magazine: 横写真主体の雑誌特集 (3-6枚)
  {
    id: "landscape_magazine_001",
    name: "ホリゾンタル・マガジン (3-6枚)",
    style: "magazine",
    supportedPhotoCount: { min: 3, max: 6 },
    aspect: "4:5",
    background: "magazine_white",
    description: "上下2段・3段のワイドフレームで横写真を雑誌のように洗練して配置",
    slots: [
      {
        role: "mainPhoto",
        x: 0.06,
        y: 0.08,
        width: 0.88,
        height: 0.40,
        rotationRange: [0, 0],
        zIndex: 1,
        preferredOrientation: "landscape",
        frameStyle: "clean",
      },
      {
        role: "secondaryPhoto",
        x: 0.06,
        y: 0.51,
        width: 0.42,
        height: 0.28,
        rotationRange: [0, 0],
        zIndex: 2,
        preferredOrientation: "landscape",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.52,
        y: 0.51,
        width: 0.42,
        height: 0.28,
        rotationRange: [0, 0],
        zIndex: 2,
        preferredOrientation: "landscape",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.06,
        y: 0.77,
        width: 0.88,
        height: 0.18,
        rotationRange: [0, 0],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "film",
        optional: true,
      },
    ],
  },

  // 13. Landscape Photo Wall: 横写真フォトウォール (4-8枚)
  {
    id: "landscape_gallery_001",
    name: "横写真フォトウォール (4-8枚)",
    style: "polaroid",
    supportedPhotoCount: { min: 4, max: 8 },
    aspect: "4:5",
    background: "notebook",
    description: "横長ポラロイド風に写真を左右2列で綺麗に敷き詰めるレイアウト",
    slots: [
      { role: "mainPhoto", x: 0.05, y: 0.08, width: 0.44, height: 0.28, rotationRange: [-2, 1], zIndex: 2, preferredOrientation: "landscape", frameStyle: "polaroid" },
      { role: "secondaryPhoto", x: 0.51, y: 0.08, width: 0.44, height: 0.28, rotationRange: [1, 4], zIndex: 3, preferredOrientation: "landscape", frameStyle: "polaroid" },
      { role: "subPhoto", x: 0.05, y: 0.38, width: 0.44, height: 0.28, rotationRange: [2, 5], zIndex: 3, preferredOrientation: "landscape", frameStyle: "polaroid" },
      { role: "subPhoto", x: 0.51, y: 0.38, width: 0.44, height: 0.28, rotationRange: [-3, 0], zIndex: 4, preferredOrientation: "landscape", frameStyle: "polaroid" },
      { role: "subPhoto", x: 0.05, y: 0.68, width: 0.44, height: 0.28, rotationRange: [-2, 2], zIndex: 5, preferredOrientation: "landscape", frameStyle: "polaroid", optional: true },
      { role: "subPhoto", x: 0.51, y: 0.68, width: 0.44, height: 0.28, rotationRange: [1, 4], zIndex: 5, preferredOrientation: "landscape", frameStyle: "polaroid", optional: true },
    ],
  },
];
