// lib/collage-templates.ts
import { CollageTemplate } from "@/types/collage-template";

export const COLLAGE_TEMPLATES: CollageTemplate[] = [
  // 1. Scrapbook: 旅の思い出をマスキングテープや手書き風ノートでコラージュ
  {
    id: "scrapbook_001",
    name: "トラベル・スクラップブック (3-5枚)",
    style: "scrapbook",
    supportedPhotoCount: { min: 3, max: 5 },
    aspect: "4:5",
    background: "craft",
    description: "クラフト紙にテープ留めと手書き風スタンプで彩る温かみのあるレイアウト",
    slots: [
      {
        role: "mainPhoto",
        x: 0.08,
        y: 0.10,
        width: 0.54,
        height: 0.52,
        rotationRange: [-3, 3],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "tape",
      },
      {
        role: "secondaryPhoto",
        x: 0.50,
        y: 0.16,
        width: 0.42,
        height: 0.38,
        rotationRange: [3, 8],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "subPhoto",
        x: 0.16,
        y: 0.58,
        width: 0.40,
        height: 0.35,
        rotationRange: [-5, -1],
        zIndex: 4,
        preferredOrientation: "square",
        frameStyle: "tape",
      },
      {
        role: "cutout",
        x: 0.54,
        y: 0.52,
        width: 0.38,
        height: 0.38,
        rotationRange: [2, 6],
        zIndex: 5,
        preferredOrientation: "any",
        frameStyle: "polaroid",
        optional: true,
      },
    ],
  },

  // 2. Magazine: 雑誌の一ページのような大胆な構図と余白
  {
    id: "magazine_001",
    name: "トラベル・マガジン (2-4枚)",
    style: "magazine",
    supportedPhotoCount: { min: 2, max: 4 },
    aspect: "4:5",
    background: "magazine_white",
    description: "雑誌の特集ページのようなモダンでスタイリッシュな大型メインレイアウト",
    slots: [
      {
        role: "mainPhoto",
        x: 0.06,
        y: 0.08,
        width: 0.88,
        height: 0.52,
        rotationRange: [0, 0],
        zIndex: 1,
        preferredOrientation: "landscape",
        frameStyle: "clean",
      },
      {
        role: "secondaryPhoto",
        x: 0.06,
        y: 0.63,
        width: 0.42,
        height: 0.31,
        rotationRange: [0, 0],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.52,
        y: 0.63,
        width: 0.42,
        height: 0.31,
        rotationRange: [0, 0],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "clean",
      },
    ],
  },

  // 3. Polaroid: ポラロイド写真を並べたような定番スタイル
  {
    id: "polaroid_001",
    name: "ポラロイド・トリップ (3-6枚)",
    style: "polaroid",
    supportedPhotoCount: { min: 3, max: 6 },
    aspect: "4:5",
    background: "clean",
    description: "白い余白フレームと少し傾いた手作り感が可愛いポラロイド配置",
    slots: [
      {
        role: "mainPhoto",
        x: 0.25,
        y: 0.08,
        width: 0.50,
        height: 0.48,
        rotationRange: [-4, 4],
        zIndex: 4,
        preferredOrientation: "portrait",
        frameStyle: "polaroid",
      },
      {
        role: "secondaryPhoto",
        x: 0.06,
        y: 0.36,
        width: 0.40,
        height: 0.38,
        rotationRange: [-9, -4],
        zIndex: 2,
        preferredOrientation: "square",
        frameStyle: "polaroid",
      },
      {
        role: "secondaryPhoto",
        x: 0.54,
        y: 0.36,
        width: 0.40,
        height: 0.38,
        rotationRange: [4, 9],
        zIndex: 3,
        preferredOrientation: "square",
        frameStyle: "polaroid",
      },
      {
        role: "subPhoto",
        x: 0.30,
        y: 0.62,
        width: 0.38,
        height: 0.34,
        rotationRange: [-3, 3],
        zIndex: 5,
        preferredOrientation: "landscape",
        frameStyle: "polaroid",
        optional: true,
      },
    ],
  },

  // 4. Messy: 重なりや傾きをあえてラフにして旅の臨場感を出す
  {
    id: "messy_001",
    name: "メッシー・スクラップ (4-7枚)",
    style: "messy",
    supportedPhotoCount: { min: 4, max: 7 },
    aspect: "4:5",
    background: "craft",
    description: "無造作に机に広げたような、あえて揃えすぎない動きのあるレイアウト",
    slots: [
      {
        role: "background",
        x: 0.08,
        y: 0.12,
        width: 0.48,
        height: 0.42,
        rotationRange: [-8, -4],
        zIndex: 1,
        preferredOrientation: "landscape",
        frameStyle: "vintage",
      },
      {
        role: "mainPhoto",
        x: 0.42,
        y: 0.08,
        width: 0.50,
        height: 0.46,
        rotationRange: [4, 8],
        zIndex: 3,
        preferredOrientation: "portrait",
        frameStyle: "polaroid",
      },
      {
        role: "secondaryPhoto",
        x: 0.12,
        y: 0.46,
        width: 0.46,
        height: 0.44,
        rotationRange: [3, 7],
        zIndex: 4,
        preferredOrientation: "portrait",
        frameStyle: "tape",
      },
      {
        role: "subPhoto",
        x: 0.48,
        y: 0.50,
        width: 0.44,
        height: 0.40,
        rotationRange: [-7, -3],
        zIndex: 2,
        preferredOrientation: "landscape",
        frameStyle: "clean",
      },
    ],
  },

  // 5. Minimal: 余白を広く取った端正なグリッド
  {
    id: "minimal_001",
    name: "ミニマル・グリッド (2-4枚)",
    style: "minimal",
    supportedPhotoCount: { min: 2, max: 4 },
    aspect: "1:1",
    background: "clean",
    description: "洗練された幾何学余白で写真そのものの美しさを引き立てる構成",
    slots: [
      {
        role: "mainPhoto",
        x: 0.06,
        y: 0.06,
        width: 0.42,
        height: 0.42,
        rotationRange: [-1, 1],
        zIndex: 1,
        preferredOrientation: "square",
        frameStyle: "clean",
      },
      {
        role: "secondaryPhoto",
        x: 0.52,
        y: 0.06,
        width: 0.42,
        height: 0.42,
        rotationRange: [-1, 1],
        zIndex: 1,
        preferredOrientation: "square",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.06,
        y: 0.52,
        width: 0.42,
        height: 0.42,
        rotationRange: [-1, 1],
        zIndex: 1,
        preferredOrientation: "square",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.52,
        y: 0.52,
        width: 0.42,
        height: 0.42,
        rotationRange: [-1, 1],
        zIndex: 1,
        preferredOrientation: "square",
        frameStyle: "clean",
        optional: true,
      },
    ],
  },

  // 6. Photo Diary: 旅日記の1ページのような構成
  {
    id: "photo_diary_001",
    name: "フォト・ダイアリー (3-5枚)",
    style: "photo_diary",
    supportedPhotoCount: { min: 3, max: 5 },
    aspect: "4:5",
    background: "notebook",
    description: "方眼ノートの背景に、日付や都市名スタンプと共に思い出を記録する旅日記",
    slots: [
      {
        role: "mainPhoto",
        x: 0.06,
        y: 0.12,
        width: 0.46,
        height: 0.76,
        rotationRange: [-2, 2],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "polaroid",
      },
      {
        role: "secondaryPhoto",
        x: 0.55,
        y: 0.15,
        width: 0.38,
        height: 0.34,
        rotationRange: [2, 5],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
      {
        role: "subPhoto",
        x: 0.55,
        y: 0.52,
        width: 0.38,
        height: 0.34,
        rotationRange: [-4, -1],
        zIndex: 3,
        preferredOrientation: "landscape",
        frameStyle: "tape",
      },
    ],
  },

  // 7. Magazine Story: ストーリーズ (9:16) 向け縦長構成
  {
    id: "magazine_story_001",
    name: "シネマ・ストーリー (3-5枚)",
    style: "magazine",
    supportedPhotoCount: { min: 3, max: 5 },
    aspect: "9:16",
    background: "dark",
    description: "スマホ全画面(9:16)で映える、シネマティックな縦長ストーリー",
    slots: [
      {
        role: "mainPhoto",
        x: 0.08,
        y: 0.06,
        width: 0.84,
        height: 0.48,
        rotationRange: [0, 0],
        zIndex: 1,
        preferredOrientation: "landscape",
        frameStyle: "film",
      },
      {
        role: "secondaryPhoto",
        x: 0.08,
        y: 0.56,
        width: 0.40,
        height: 0.36,
        rotationRange: [-2, 2],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "clean",
      },
      {
        role: "subPhoto",
        x: 0.52,
        y: 0.56,
        width: 0.40,
        height: 0.36,
        rotationRange: [-2, 2],
        zIndex: 2,
        preferredOrientation: "portrait",
        frameStyle: "clean",
      },
    ],
  },
];
